import { format } from "date-fns";
import { APP_USER } from "@/lib/workspace";
import { getExpenses, getFoodDecisions, getMessages } from "@/lib/data";
import {
  createWeeklyLifeReport,
  findSubscriptions,
} from "@/lib/premium-insights";

const escapePdfText = (value: string) =>
  value
    .replace(/[^\x20-\x7E]/g, "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

const text = (
  value: string,
  x: number,
  y: number,
  size = 12,
  font = "F1",
  color = "0.24 0.07 0.16",
) =>
  `BT ${color} rg /${font} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${escapePdfText(value)}) Tj ET`;

function createPdf(lines: string[]) {
  const stream = lines.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";

  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf);
}

export async function GET() {
  const [expenses, foods, messages] = await Promise.all([
    getExpenses(APP_USER.id),
    getFoodDecisions(APP_USER.id),
    getMessages(APP_USER.id),
  ]);
  const report = createWeeklyLifeReport(expenses, foods, messages);
  const subscriptions = findSubscriptions(expenses);
  const pdf = createPdf([
    "0.96 0.34 0.62 rg 0 700 612 92 re f",
    "1 0.88 0.94 rg 0 0 612 700 re f",
    text("LifeOps", 48, 752, 16, "F2", "1 1 1"),
    text("Weekly Life Report", 48, 724, 28, "F2", "1 1 1"),
    text(format(new Date(report.generatedAt), "d MMMM yyyy"), 48, 670, 11),
    text(`A gentle review for ${APP_USER.name}`, 48, 648, 16, "F2"),
    text("THIS WEEK", 48, 602, 10, "F2", "0.74 0.16 0.38"),
    text(`Spent: INR ${report.spent.toLocaleString("en-IN")}`, 48, 574, 14, "F2"),
    text(`Most ordered: ${report.mostOrdered}`, 48, 548, 12),
    text(`Top category: ${report.topCategory}`, 48, 524, 12),
    text(`Most used message: ${report.mostUsedMessage}`, 48, 500, 12),
    text(`Biggest win: ${report.biggestWin}`, 48, 476, 12),
    "0.94 0.70 0.80 rg 48 426 516 1 re f",
    text("SUBSCRIPTION HUNTER", 48, 392, 10, "F2", "0.74 0.16 0.38"),
    ...subscriptions.map((subscription, index) =>
      text(
        `${subscription.merchant}: INR ${subscription.amount.toLocaleString("en-IN")} / month`,
        48,
        364 - index * 22,
        12,
      ),
    ),
    text(
      `Monthly recurring total: INR ${report.subscriptionsTotal.toLocaleString("en-IN")}`,
      48,
      272,
      14,
      "F2",
    ),
    text(
      "Small patterns become calmer weeks. Keep checking in.",
      48,
      116,
      12,
      "F2",
      "0.74 0.16 0.38",
    ),
    text("Generated by LifeOps", 48, 88, 10),
  ]);

  return new Response(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'attachment; filename="lifeops-weekly-report.pdf"',
    },
  });
}
